version: "3"
services:
  db:
    image: "postgres"
    container_name: gudbuks_db
    environment:
      POSTGRES_PASSWORD: devonly
      POSTGRES_USER: admin
      POSTGRES_DB: gudbuks
    ports:
      - "5432:5432"
